#!/usr/local/bin/perl -p -i~

BEGIN { # {

sub usage { die "Usage: chcite old=new [filename]\n"; }
usage if ($#ARGV < 0);

$cite_chars = "A-Za-z0-9_:";
$cite_re = qr/^[$cite_chars]+$/;
%cites = ();  @bad = ();
while ($ARGV[0] =~ /(.+)=(.+)/) {
	shift @ARGV;
	foreach ($1, $2) {
		if (! $1 =~ $cite_re)		{ push(@bad_cites, $1); }
		elsif (! $2 =~ $cite_re)	{ push(@bad_cites, $2); }
		else				{ $cites{$1} = $2; }
	}
}
print STRERR "Warning: Skipped improper references: "
   . join(" ",@bad_cites) . "\n" if (@bad);
shift if ($ARGV[0] eq "--");

sub f {
	return join(",",
		map { $cites{$_} ? $cites{$_} : $_ } split(/,/,$_[0]) );
}

} # } BEGIN

s/\\cite(\[[^\[\]]*\])?\{([$cite_chars,]+)\}/ "\\cite$1\{" . &f($2) . "\}" /eg;

END { # {
} # } END

